# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54cb3ea71fc85a7113e8155fbd52f62b8377ea047ca1e774010cc2ee93242486525b01f186dc1054557110db06342c178ea79a3c7ed98045fb820b09e5f9ccb4

test:
  secret_key_base: 138747129f325e90857593f843daf80ce8483d8bf3fb76a72e19c61be359037ba229eb8a6e4482c332f0d762acab905dcee283e871c76172cbfbe0a42bb4437c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
